name: Boerenjongens
favicon: null
layout_spectrum: 0.01598
typography_spectrum: 0.24728
title: Boerenjongens is een creatief full service communicatiebureau
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#182325'
    - '#bfbfb3'
    - '#424d4f'
    - '#a47b4f'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
