name: Boerenjongens
favicon: null
layout_spectrum: 0.98482
typography_spectrum: 0
title: Boerenjongens is een creatief full service communicatiebureau
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#e84711'
    - '#44978d'
    - '#ffffff'
    - '#cad401'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
